//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraJob) DeepCopyInto(out *CassandraJob) {
	*out = *in
	in.Arguments.DeepCopyInto(&out.Arguments)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraJob.
func (in *CassandraJob) DeepCopy() *CassandraJob {
	if in == nil {
		return nil
	}
	out := new(CassandraJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraTask) DeepCopyInto(out *CassandraTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraTask.
func (in *CassandraTask) DeepCopy() *CassandraTask {
	if in == nil {
		return nil
	}
	out := new(CassandraTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraTaskList) DeepCopyInto(out *CassandraTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CassandraTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraTaskList.
func (in *CassandraTaskList) DeepCopy() *CassandraTaskList {
	if in == nil {
		return nil
	}
	out := new(CassandraTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraTaskSpec) DeepCopyInto(out *CassandraTaskSpec) {
	*out = *in
	out.Datacenter = in.Datacenter
	in.CassandraTaskTemplate.DeepCopyInto(&out.CassandraTaskTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraTaskSpec.
func (in *CassandraTaskSpec) DeepCopy() *CassandraTaskSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraTaskStatus) DeepCopyInto(out *CassandraTaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraTaskStatus.
func (in *CassandraTaskStatus) DeepCopy() *CassandraTaskStatus {
	if in == nil {
		return nil
	}
	out := new(CassandraTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraTaskTemplate) DeepCopyInto(out *CassandraTaskTemplate) {
	*out = *in
	if in.ScheduledTime != nil {
		in, out := &in.ScheduledTime, &out.ScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]CassandraJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraTaskTemplate.
func (in *CassandraTaskTemplate) DeepCopy() *CassandraTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(CassandraTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobArguments) DeepCopyInto(out *JobArguments) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JobsCount != nil {
		in, out := &in.JobsCount, &out.JobsCount
		*out = new(int)
		**out = **in
	}
	if in.NewTokens != nil {
		in, out := &in.NewTokens, &out.NewTokens
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobArguments.
func (in *JobArguments) DeepCopy() *JobArguments {
	if in == nil {
		return nil
	}
	out := new(JobArguments)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledTask) DeepCopyInto(out *ScheduledTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledTask.
func (in *ScheduledTask) DeepCopy() *ScheduledTask {
	if in == nil {
		return nil
	}
	out := new(ScheduledTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledTaskList) DeepCopyInto(out *ScheduledTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduledTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledTaskList.
func (in *ScheduledTaskList) DeepCopy() *ScheduledTaskList {
	if in == nil {
		return nil
	}
	out := new(ScheduledTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledTaskSpec) DeepCopyInto(out *ScheduledTaskSpec) {
	*out = *in
	in.TaskDetails.DeepCopyInto(&out.TaskDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledTaskSpec.
func (in *ScheduledTaskSpec) DeepCopy() *ScheduledTaskSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledTaskStatus) DeepCopyInto(out *ScheduledTaskStatus) {
	*out = *in
	in.NextSchedule.DeepCopyInto(&out.NextSchedule)
	in.LastExecution.DeepCopyInto(&out.LastExecution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledTaskStatus.
func (in *ScheduledTaskStatus) DeepCopy() *ScheduledTaskStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDetails) DeepCopyInto(out *TaskDetails) {
	*out = *in
	in.CassandraTaskSpec.DeepCopyInto(&out.CassandraTaskSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDetails.
func (in *TaskDetails) DeepCopy() *TaskDetails {
	if in == nil {
		return nil
	}
	out := new(TaskDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskResult) DeepCopyInto(out *TaskResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskResult.
func (in *TaskResult) DeepCopy() *TaskResult {
	if in == nil {
		return nil
	}
	out := new(TaskResult)
	in.DeepCopyInto(out)
	return out
}
