# Download docker images
# Load docker images
name: run-integration-test
description: "Run integration test"
inputs:
  integration_test:
    description: "M_INTEG_DIR value"
    required: true
  serverVersion:
    description: "Override server version used in the test file"
    required: false
  serverImage:
    description: "Override server image used in the test file"
    required: false
  GITHUB_TOKEN:
    description: "GitHub Token (used by Helm action)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Free diskspace by removing unused packages
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-integ-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-integ-
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.3.0
      with:
        version: v0.14.0
        node_image: kindest/node:v1.24.3
        cluster_name: kind
        config: tests/testdata/kind/kind_config_6_workers.yaml
    - name: Install Helm
      uses: azure/setup-helm@v3
      id: install_helm
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - name: Download cass-operator image
      uses: actions/download-artifact@v2
      with:
        name: cass-operator
        path: /tmp
    - name: Download system-logger image
      uses: actions/download-artifact@v2
      with:
        name: system-logger
        path: /tmp
    - name: Load Docker images
      shell: bash
      run: |
        docker load --input /tmp/k8ssandra-cass-operator.tar
        docker load --input /tmp/k8ssandra-system-logger.tar
    - name: Load image on the nodes of the cluster
      shell: bash
      run: |
        kind load docker-image --name=kind us-docker.pkg.dev/k8ssandra/images/cass-operator:latest
        kind load docker-image --name=kind us-docker.pkg.dev/k8ssandra/images/system-logger:latest
    - name: Run integration test ( ${{ inputs.integration_test }} )
      shell: bash
      run: |
        IMG=us-docker.pkg.dev/k8ssandra/images/cass-operator:latest make integ-test
