# permissions for end users to edit scheduledtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cass-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtask.k8ssandra.io-scheduledtask-editor-role
rules:
- apiGroups:
  - scheduledtask.k8ssandra.io.cassandra.datastax.com
  resources:
  - scheduledtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduledtask.k8ssandra.io.cassandra.datastax.com
  resources:
  - scheduledtasks/status
  verbs:
  - get
