## Append samples you want in your CSV to this file as resources ##
resources:
- example-cassdc-three-nodes-single-rack.yaml
- cassandratask-cleanup.yaml
- scheduledtask.k8ssandra.io_v1alpha1_scheduledtask.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
