apiVersion: scheduledtask.k8ssandra.io.cassandra.datastax.com/v1alpha1
kind: ScheduledTask
metadata:
  labels:
    app.kubernetes.io/name: cass-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtask-sample
spec:
  # TODO(user): Add fields here
